import { AnalysisResult } from './api';

export function downloadAnalysisReport(analysisResult: AnalysisResult, filePath: string) {
  const smells = analysisResult.smells || analysisResult.issues || [];
  const steps = analysisResult.refactoring_plan?.refactoring_steps || [];

  const markdownContent = `# 🛡️ ONGISA Code Analysis & Refactoring Report
  
**Generated on:** ${new Date().toLocaleString()}  
**Target File:** \`${filePath || 'N/A'}\`  
**Total Smells Detected:** ${smells.length}  

---

## 🔍 Detected Code Smells & Issues

${smells.length === 0 ? '*No code smells detected! Clean architecture.*' : smells.map(s => `
- **[${s.severity.toUpperCase()}]** Line ${s.line} — **${s.type}**
  - *Message:* ${s.message}${s.description ? `- *Description:* ${s.description}` : ''}
`).join('\n')}

---

## 💡 Recommended Refactoring Plan

${steps.length === 0 ? '*No refactoring steps required.*' : steps.map((step, idx) => `
### Step ${idx + 1}: ${step.action} (Line${step.target_line})
- **Description:** ${step.description}
- **Suggestion:** \`${step.suggestion}\`
`).join('\n')}

---
*Report automatically generated by ONGISA Forge Platform.*
`;

  const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `ongisa-report-${Date.now()}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}